# Generated by Django 3.1.7 on 2021-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_album_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='self',
            field=models.URLField(default=1, verbose_name='HOLA'),
            preserve_default=False,
        ),
    ]
