# Generated by Django 3.1.7 on 2021-04-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_artista_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='self',
        ),
    ]
