# Generated by Django 3.1.7 on 2021-04-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_remove_artista_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='test',
            field=models.CharField(default='WASAP', max_length=200),
        ),
    ]
