# Generated by Django 3.1.7 on 2021-04-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_artista_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='test',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
