# Generated by Django 3.1.7 on 2021-04-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0006_auto_20210429_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='test',
        ),
    ]
