# Generated by Django 3.1.7 on 2021-04-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0008_artista_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='albums',
        ),
    ]
