# Generated by Django 3.1.7 on 2021-04-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0009_remove_artista_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='albums',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='self',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='tracks',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
