# Generated by Django 3.1.7 on 2021-04-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0010_auto_20210429_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='self',
            new_name='self_artist',
        ),
    ]
