# Generated by Django 3.1.7 on 2021-04-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0013_auto_20210430_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='self',
            new_name='self_artista',
        ),
    ]
