# Generated by Django 3.1.7 on 2021-05-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0014_auto_20210430_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='self_artista',
            new_name='self',
        ),
    ]
