# Generated by Django 3.1.7 on 2021-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0016_auto_20210502_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='self_album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='self_track',
        ),
        migrations.AddField(
            model_name='album',
            name='self',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='self',
            field=models.URLField(blank=True),
        ),
    ]
